
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Install dependencies using npm (ci ensures a clean install based on package-lock.json)
      - name: Install dependencies
        run: npm ci
      
      # Step 3: Build the project (if needed, adjust if you're using a different build command)
      - name: Build project
        run: npm run build
      
      # Step 4: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }} # Access GitHub secrets for authentication
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_CRM_E368D }} # Your Firebase service account secret
          channelId: live # Deploy to the live channel
          projectId: fir-crm-e368d # Your Firebase project ID
